### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by tytyalx** [MicroWeaR/MicroWeaR#2]
>devtools::install_github("MicroWeaR/MicroWeaR",local=FALSE)
Error in read.dcf(path) : 
  Found continuation line starting '        2.5.1), zoom ...' at begin of record.

**Comment by FrancesForrest** [comment]
Have you had any luck with this? I am having the same issue.

**Comment by MicroWeaR** [comment]
I corrected the Description file, there was an extra space in the import section.

Please try this code for the installation of R MicroWear package:

```
install.packages("devtools")
library("devtools")
install.packages("zoom")
library(zoom)
install.packages("RANN")
library(RANN)
install_github("MicroWeaR/MicroWeaR",local=FALSE)
library(MicroWeaR)
```

Antonio

**Comment by FrancesForrest** [comment]
Thank you. That worked perfectly!

**Comment by FrancesForrest** [comment]
Hi Antonio, 

I am still having a bit of trouble with the package and wondering if you can help. I am able to get the package running in R but when the image comes up i see three windows with the same image and it is quite distorted. See the attached image. Do you have any suggestions? 
![2018-11-21](https://user-images.githubusercontent.com/45145392/48864048-63815680-ed99-11e8-8914-b197b27656b4.png)

**Comment by FrancesForrest** [comment]
This is what the image should look like.
![82158_mandible_b_bw](https://user-images.githubusercontent.com/45145392/48864179-c2df6680-ed99-11e8-8376-0f5b1d431c2a.jpg)
